# Generated by Django 4.1.5 on 2023-01-04 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImagesPro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
                ('thumbnial', models.ImageField(blank=True, upload_to='images')),
                ('medium', models.ImageField(blank=True, upload_to='images')),
                ('large', models.ImageField(blank=True, upload_to='images')),
                ('grayscale', models.ImageField(blank=True, upload_to='images')),
            ],
        ),
    ]
